var team_access = '<section class="team_banar_area">';
 team_access += '<div class="team_banar_inner">';
 team_access += '<img src="../assets/img/team_img/team_banar_art-1.svg" alt="" class="banar_art_1" style="position: absolute;">';
 team_access += '<img src="../assets/img/team_img/team_banar_art-2.svg" alt="" class="banar_art_2" style="position: absolute;">';
 team_access += '<div class="team_banar_content text-center">';
 team_access += '<h1 class="inner_banar_title text-white xtramargin xtraxtramargin">The XP.network Team</h1>';
 team_access += '<p class="sec_t owc">Meet the visionary leaders, experts, and professionals behind the first blockchain-agnostic NFT ecosystem</p>';
 /*team_access += '<a href="javescript:void(0)"class="blueT_btn popupBtn">Join our team <img src="../assets/img/icons/blue_arrow.svg" alt="icon"></a>';*/
 team_access += '</div> </div> </section>';

 team_access += '<section class="team_area">';
 team_access += '<img src="../assets/img/team_img/team_art_3.svg" alt="" class="team_art_img">';
 team_access += '<div class="team_container">';
 team_access += '<div class="row">';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/nir.jpg" alt=""></div> <h4 class="sm_tit">Nir Blumberger</h4> <p class="sec_t">CEO & Co-Founder</p> <p>Former executive at AmaZix, Former executive at Firmo <br>(acquired by eToro)</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/nir-blumberger-714168155/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Dima_b.png" alt=""></div> <h4 class="sm_tit">Dima Briukhanov</h4> <p class="sec_t">CTO</p> <p>Years of development experience in C, C++, Rust and Solidity</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/dmitry-briukhanov-60b2ab45/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/team-image-3.png" alt=""></div> <h4 class="sm_tit">Verbal Kint</h4> <p class="sec_t">Engineer & Co-Founder</p> <p>Blockchain engineer, built a successful Ethereum DApp. Extreme prototyper and Move and Rust enthusiast</p> <ul class="team_social"> <li></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Ditry_u.png" alt=""></div> <h4 class="sm_tit">Dmitry Ulyanov</h4> <p class="sec_t">COO</p> <p>Senior team leader. 12 years of impeccable team managing experience in high-tech companies and international brands</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/dimaulyanov/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Idan_B.png" alt=""></div> <h4 class="sm_tit">Idan Bar Shalom </h4> <p class="sec_t">CFO</p> <p>CPA. Former CFO at Firmo (acquired by eToro)</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/idan-bar-shalom-2ba03b85/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/yaron.jpg" alt=""></div> <h4 class="sm_tit">Yaron Levy </h4> <p class="sec_t">Operations & Legal </p> <p>Adv. Yaron Levy is a seasoned lawyer experienced in commercial law</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Daniel_M.png" alt=""></div> <h4 class="sm_tit">Daniel Mittelstadt</h4> <p class="sec_t">Product Architecture</p> <p>Seasoned product architect, expertise in heavily regulated markets</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/daniel-mittelstadt-317008156/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/julia.png" alt=""></div> <h4 class="sm_tit">Yulia Prototska</h4> <p class="sec_t">Art Director </p> <p>Leading XP design. On the mission of making blockchain technology accessible and easy to use</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/julia-prototskaya-84a15238/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Loredana.png" alt=""></div> <h4 class="sm_tit">Loredana Stupurac </h4> <p class="sec_t">Partnerships & Growth</p> <p>Growing the XP ecosystem. Building partnerships, KOL relations and head of the Ambassadorship program</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/loredana-dobre-stupurac-854260183/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 /*team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/avatar.png" alt=""></div> <h4 class="sm_tit">Hili Yaakobi </h4> <p class="sec_t">Art Director</p> <p>Lorem ipsum</p> <ul class="team_social"> <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';*/
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/avatar.png" alt=""></div> <h4 class="sm_tit">Reuven Bitton</h4> <p class="sec_t">Full Stack Engineer</p> <p>Reuven has 15+ years of experience in developing backend systems</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/AlexM.png" alt=""></div> <h4 class="sm_tit">Alex Moshinsky</h4> <p class="sec_t">Front End Developer</p> <p>Passionate for user-friendly web and mobile applications</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/alex1mosh/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Rupansh.png" alt=""></div> <h4 class="sm_tit">Rupansh Sekar </h4> <p class="sec_t">Blockchain Engineer</p> <p>C++ and Rust developer </p> <ul class="team_social"> <li><a href=" https://www.linkedin.com/in/rupansh-sekar-10941b16a/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Waseem.png" alt=""></div> <h4 class="sm_tit">Waseem Ahmed Tunio</h4> <p class="sec_t">Senior Full Stack Software Engineer</p> <p>Experienced user interface developer</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Michael.png" alt=""></div> <h4 class="sm_tit">Michael Dagan</h4> <p class="sec_t">Community Lead</p> <p>Social and communication expert</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/michael-dagan-155320209/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Greg.png" alt=""></div> <h4 class="sm_tit">Greg Chapman</h4> <p class="sec_t">Community Manager</p> <p>Building a strong relationship with our community on all socials</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/gregory-chapman-112460144/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Brian.png" alt=""></div> <h4 class="sm_tit">Brian Colon </h4> <p class="sec_t"> Community Manager</p> <p>Building a strong relationship with our community on all socials</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/beekeyyy/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Alisa.png" alt=""></div> <h4 class="sm_tit">Alisa Orlova </h4> <p class="sec_t">Content</p> <p>Heading messaging and communication across all channels</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card" id="advisors"> <div class="team_img"><img src="../assets/img/team_img/Stas.png" alt=""></div> <h4 class="sm_tit">Stas Oskin</h4> <p class="sec_t">Advisor</p> <p>Stas has 15 years of experience in IT engineering, development, and project management. Previously founded Wing.ai and Dfinance, Co-Founder of Pontem Network</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/stasoskin/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Sheridan.png" alt=""></div> <h4 class="sm_tit">Sheridan Hammond</h4> <p class="sec_t">Advisor</p> <p>Sheridan founded the Australian investment firm Kosmos Ventures, focused on helping promising blockchain startups scale and integrate their technology into our common future. Kosmos Ventures was among the early backers of Algorand, Solana and Polkadot</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/sheridanhammond/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/Kyle.png" alt=""></div> <h4 class="sm_tit">Kyle Chasse</h4> <p class="sec_t">Advisor</p><p>Kyle is a blockchain industry veteran, a prominent Bitcoin investor since 2013, and a sought-after keynote speaker. Kyle invested in projects like Kraken, Coinbase, Bitfinex, and others. He founded Master Ventures, a blockchain advisory firm that has worked Tier-1 startups such as UBANX, Spl.yt, and PAID Network</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/kylechasse/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '</div> </div> </section>';
 team_access += '<section id="apply" class="get_in_tuch_area"> <div class="get_in_tuch_container"> <h2 class="secTitle tcb text-center">Get in touch with us and step up your career</h2> <p class="sec_t">If you care deeply about what we are building and think you are a <br>great fit, wed love to hear from you. <br>Don’t be shy – apply!</p> <span class="blue_btn_2 popupBtns butondisabl">Apply for a job</span> </div> </section>';	
 team_access += '<div class="applicationPopup"> <div class="application_container"> <div class="formTitle"> <h2>Submit your application</h2> <span class="close_pop"><img src="../assets/img/close-pop.svg" alt=""></span> </div><form action="#" id="jbForm"> <div class="row"> <div class="col-md-6"> <div class="inputs"> <input type="text" name="first_name" id="first_name" placeholder="First Name*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="last_name" id="last_name" placeholder="Last Name*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="email" name="yourEmail" id="yourEmail" placeholder="Email*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="number" name="phone_number" id="phone_number" placeholder="Phone number" > </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="currentPositon" id="currentPositon" placeholder="Current position"> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="currentCompany" id="currentCompany" placeholder="Current company"> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="linkedinLink" id="linkedinLink" placeholder="Link on Linkedin"> </div></div><div class="col-md-6"> <div class="inputs resumelabel">  <label for="attatchResume"> Attach Resume / CV <img src="../assets/img/plus.svg" alt=""> </label><input type="file" name="attatchResume" id="attatchResume"> </div></div><div class="col-md-12"> <div class="inputs"> <textarea name="additionalComent" id="additionalComent" rows="4" placeholder="Additional comments"></textarea> </div></div><div class="col-12"> <div class="submit_job"> <a href="mailto:jobs@xp.network" class="button" >Submit</a> </div></div></div></form> </div></div>';
 team_access += '<div class="thanksPopUp"> <div class="thanksContent"> <img src="../assets/img/thanks.svg"> <h3>Thank you!</h3> <p>We recived your application and will contact you soon.</p><span class="thanks_close blue_btn_2">OK</span> </div></div>';
	
	
jQuery(document).ready(function(){
//setTimeout(function(){
	jQuery("#team_bodies").html(team_access);
//},1000);		
});