var team_access = '<section class="team_banar_area">';
 team_access += '<div class="team_banar_inner">';
 team_access += '<img src="/assets/img/team_img/team_banar_art-1.svg" alt="" class="banar_art_1" style="position: absolute;">';
 team_access += '<img src="/assets/img/team_img/team_banar_art-2.svg" alt="" class="banar_art_2" style="position: absolute;">';
 team_access += '<div class="team_banar_content text-center">';
 team_access += '<h1 class="inner_banar_title text-white xtramargin xtraxtramargin">XP.network团队</h1>';
 team_access += '<p class="sec_t owc">区块链不可知NFT生态系统背后的贡献者 — 卓越的领导者、<br>专家和专业人士团队</p>';
 /*team_access += '<a href="javescript:void(0)"class="blueT_btn popupBtn">Join our team <img src="../assets/img/icons/blue_arrow.svg" alt="icon"></a>';*/
 team_access += '</div> </div> </section>';

 team_access += '<section class="team_area">';
 team_access += '<img src="/assets/img/team_img/team_art_3.svg" alt="" class="team_art_img">';
 team_access += '<div class="team_container">';
 team_access += '<div class="row">';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/nir.jpg" alt=""></div> <h4 class="sm_tit">Nir Blumberger</h4> <p class="sec_t">首席执行官兼联合创始人</p> <p>AmaZix前高管，Firmo前高管 <br>（已被eToro收购）</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/nir-blumberger-714168155/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Dima_b.png" alt=""></div> <h4 class="sm_tit">Dima Briukhanov</h4> <p class="sec_t">首席技术官</p> <p>拥有多年C、C++、Rust和Solidity开发经验</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/dmitry-briukhanov-60b2ab45/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/team-image-3.png" alt=""></div> <h4 class="sm_tit">Verbal Kint</h4> <p class="sec_t">工程师兼联合创始人</p> <p>enthusiast区块链工程师，成功构建了以太坊DApp。优秀原型设计者，热衷于Move和 Rust</p> <ul class="team_social"> <li></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Ditry_u.png" alt=""></div> <h4 class="sm_tit">Dmitry Ulyanov</h4> <p class="sec_t">首席运营官</p> <p>资深团队负责人。在高端科技公司和国际品牌企业有着12年的团队管理经验</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/dimaulyanov/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Idan_B.png" alt=""></div> <h4 class="sm_tit">Idan Bar Shalom </h4> <p class="sec_t">首席财务官</p> <p>注册会计师，Firmo（已被eToro收购）前首席财务官</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/idan-bar-shalom-2ba03b85/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/yaron.jpg" alt=""></div> <h4 class="sm_tit">Yaron Levy </h4> <p class="sec_t">运营与法律顾问</p> <p>Yaron Levy是一位经验丰富的商法律师</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Daniel_M.png" alt=""></div> <h4 class="sm_tit">Daniel Mittelstadt</h4> <p class="sec_t">产品建筑师</p> <p>产品建筑师，在监管严格的市场中拥有丰富的工作经验</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/daniel-mittelstadt-317008156/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/julia.png" alt=""></div> <h4 class="sm_tit">Yulia Prototska</h4> <p class="sec_t">艺术总监 </p> <p>领先的XP设计师，致力于打造易于访问和使用的区块链技术</p> <ul class="team_social"> <li><a target="_blank" href="https://www.linkedin.com/in/julia-prototskaya-84a15238/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Loredana.png" alt=""></div> <h4 class="sm_tit">Loredana Stupurac </h4> <p class="sec_t">合作与成长</p> <p>发展XP生态系统。负责合作伙伴关系和KOL关系，是媒介大使计划的负责人</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/loredana-dobre-stupurac-854260183/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 /*team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="../assets/img/team_img/avatar.png" alt=""></div> <h4 class="sm_tit">Hili Yaakobi </h4> <p class="sec_t">Art Director</p> <p>Lorem ipsum</p> <ul class="team_social"> <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';*/
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/avatar.png" alt=""></div> <h4 class="sm_tit">Reuven Bitton</h4> <p class="sec_t">全栈工程师</p> <p>Reuven拥有超过15 年的后端系统开发经验</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/AlexM.png" alt=""></div> <h4 class="sm_tit">Alex Moshinsky</h4> <p class="sec_t">前端开发人员</p> <p>热衷于开发简单易用的网络和移动应用程序</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/alex1mosh/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Rupansh.png" alt=""></div> <h4 class="sm_tit">Rupansh Sekar </h4> <p class="sec_t">区块链工程师</p> <p>C++和Rust开发人员</p> <ul class="team_social"> <li><a href=" https://www.linkedin.com/in/rupansh-sekar-10941b16a/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Waseem.png" alt=""></div> <h4 class="sm_tit">Waseem Ahmed Tunio</h4> <p class="sec_t">高级全栈软件工程师</p> <p>经验丰富的用户界面开发人员</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Michael.png" alt=""></div> <h4 class="sm_tit">Michael Dagan</h4> <p class="sec_t">社区负责人</p> <p>社交与沟通专家</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/michael-dagan-155320209/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Greg.png" alt=""></div> <h4 class="sm_tit">Greg Chapman</h4> <p class="sec_t">社区管理员</p> <p>为我们的社区建立牢固的社交关系</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/gregory-chapman-112460144/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Brian.png" alt=""></div> <h4 class="sm_tit">Brian Colon </h4> <p class="sec_t"> 社区管理员</p> <p>为我们的社区建立牢固的社交关系</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/beekeyyy/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Alisa.png" alt=""></div> <h4 class="sm_tit">Alisa Orlova </h4> <p class="sec_t">内容管理</p> <p>负责所有渠道的信息传递和沟通</p> <ul class="team_social"> <li><a href="#" style="pointer-events:none;"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card" id="advisors"> <div class="team_img"><img src="/assets/img/team_img/Stas.png" alt=""></div> <h4 class="sm_tit">Stas Oskin</h4> <p class="sec_t">顾问</p> <p>Stas在IT工程、开发和项目管理方面拥有15年的工作经验。曾创立Wing.ai和Dfinance，是 Pontem Network的联合创始人</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/stasoskin/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Sheridan.png" alt=""></div> <h4 class="sm_tit">Sheridan Hammond</h4> <p class="sec_t">顾问</p> <p>Sheridan成立了澳大利亚公司Kosmos Ventures，主要帮助有前景的区块链初创公司进行扩展，积极促进他们的技术发展，共创繁荣未来。Kosmos Ventures是Algorand、Solana和Polkadot的初期支持者之一</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/sheridanhammond/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '<div class="col-lg-4 col-md-6 col-sm-12 mb-4"> <div class="team_card"> <div class="team_img"><img src="/assets/img/team_img/Kyle.png" alt=""></div> <h4 class="sm_tit">Kyle Chasse</h4> <p class="sec_t">顾问</p><p>Kyle是区块链行业的资深人士，自2013年以来一直是比特币的积极投资者，也是广受欢迎的主题演讲者。Kyle已投资Kraken、Coinbase、Bitfinex等项目。他创立了区块链咨询公司Master Ventures，曾与UBANX、Spl.yt 和 PAID Network等顶级初创公司合作</p> <ul class="team_social"> <li><a href="https://www.linkedin.com/in/kylechasse/"><i class="fab fa-linkedin-in"></i></a></li> </ul> </div> </div>';
 team_access += '</div> </div> </section>';
 team_access += '<section id="apply" class="get_in_tuch_area"> <div class="get_in_tuch_container"> <h2 class="secTitle tcb text-center">联系我们，加入我们</h2> <p class="sec_t">如果你对我们的项目感兴趣，且自认为是最佳人选，那就快联系我们吧。 <br>不要害羞 — 快来申请!</p> <span class="blue_btn_2 popupBtns butondisabl">申请职位</span> </div> </section>';	
 team_access += '<div class="applicationPopup"> <div class="application_container"> <div class="formTitle"> <h2>Submit your application</h2> <span class="close_pop"><img src="/assets/img/close-pop.svg" alt=""></span> </div><form action="#" id="jbForm"> <div class="row"> <div class="col-md-6"> <div class="inputs"> <input type="text" name="first_name" id="first_name" placeholder="First Name*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="last_name" id="last_name" placeholder="Last Name*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="email" name="yourEmail" id="yourEmail" placeholder="Email*" required> </div></div><div class="col-md-6"> <div class="inputs"> <input type="number" name="phone_number" id="phone_number" placeholder="Phone number" > </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="currentPositon" id="currentPositon" placeholder="Current position"> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="currentCompany" id="currentCompany" placeholder="Current company"> </div></div><div class="col-md-6"> <div class="inputs"> <input type="text" name="linkedinLink" id="linkedinLink" placeholder="Link on Linkedin"> </div></div><div class="col-md-6"> <div class="inputs resumelabel">  <label for="attatchResume"> Attach Resume / CV <img src="../assets/img/plus.svg" alt=""> </label><input type="file" name="attatchResume" id="attatchResume"> </div></div><div class="col-md-12"> <div class="inputs"> <textarea name="additionalComent" id="additionalComent" rows="4" placeholder="Additional comments"></textarea> </div></div><div class="col-12"> <div class="submit_job"> <a href="mailto:jobs@xp.network" class="button" >Submit</a> </div></div></div></form> </div></div>';
 team_access += '<div class="thanksPopUp"> <div class="thanksContent"> <img src="/assets/img/thanks.svg"> <h3>Thank you!</h3> <p>We recived your application and will contact you soon.</p><span class="thanks_close blue_btn_2">OK</span> </div></div>';
	
	
jQuery(document).ready(function(){
//setTimeout(function(){
	jQuery("#team_bodies").html(team_access);
//},1000);		
});