var main_sect = ''
	main_sect += '<section class="home_hero_are">';
	main_sect += '<div class="home_he_container">';
	main_sect += '<h1 class="hero_title">Create and deploy <br>NFT dApps on <span> ';
	main_sect +='<div id="app"></div>';
	main_sect+='</span></h1>';
	main_sect += '<p>The first Blockchain-Agnostic Platform for building <br>NFT dApps</p>';
	main_sect += '<div class="banar_btns">';
	main_sect += '<a href="/xpnet" class="black_btn">Discover XPNET <img src="assets/img/arrow-w.svg"></a>';
	main_sect +='<a href="https://t.me/xp_network" class="blueT_btn">Join community <img src="assets/img/icons/blue_arrow.svg" alt="icon"></a>';
	main_sect +='</div>';
	main_sect +='</div>';
	main_sect +='<div class="soft_image">';
	main_sect +='<img class="deskonly"src="assets/img/xp_editor_ui.png" alt="Software Ui"> <img class="mobileonly" src="assets/img/xp_editor_ui.png" alt="Software Ui">';
	main_sect +='</div>';
	main_sect +='</section>';
	main_sect +='<section class="softer_design_area">';
	main_sect +='<div class="softer_design_area_inner">';
	main_sect +=' <img src="assets/img/art_images/blue_art_1.svg" alt="" class="blue_art_1">';
	main_sect +='<img src="assets/img/art_images/transp_art_1.svg" alt="" class="transp_art_1">';
	main_sect +='<div class="software_container">';
	main_sect +='<div class="software_content">';
	main_sect +='<h5 class="blue_title">go Blockchain-agnostic</h5>';
	main_sect +='<h2 class="secTitle text-white">Design, deploy, migrate - with  <br> or without code</h2>';
	main_sect +='<div class="row software_art_row">';
	main_sect +='<div class="col-lg-6 software_art">';
	main_sect +='<p>Many blockchains support NFTs, but which one is best for your project? With XP.network, you can try them all. Build a dApp without code using the graphic editor or write it in your favorite programming language, then deploy to any chain you want.</p>';
	main_sect +='</div>';
	main_sect +='<div class="col-lg-6 software_art">';
	main_sect +='<p>Want to migrate? No problem. XP.network allows you to move a dApp to another chain with a single click. We support Diem, Ethereum, Polkadot, BSC, Cardano, Solana, Elrond, Avalanche, and Heco (more are coming soon).</p>';
	main_sect +='</div>';
	main_sect +='</div>';
	main_sect +='<a target="_blank" href="https://www.figma.com/proto/ZmDl5rtvpQBzn3bx26a50m/xp.net-ui?node-id=1%3A2579&starting-point-node-id=1%3A2579" class="blue_btn">Try demo <img src="assets/img/icons/arrow-white.svg" alt="arrow"></a>';
	main_sect +='</div>';
	main_sect +='</div>';
	main_sect +='</div>';
	main_sect +='</section>';
	main_sect +='<section class="transfer_area"><div class="transferContainer"><div class="transferCon_left">';
	main_sect +='<div class="transferCon_title"> <h5 class="blue_title">Cross-Chain Bridge</h5> <h2 class="secTitle tcb">Transfer assets faster. <br>Much faster.</h2> <p class="sec_t">With the XP.network cross-chain bridge, you can quickly transfer NFTs between blockchains. Try it out right now with the fun demo – regular token transfers are coming soon!</p></div>';
	main_sect +='<div class="row custome_row">';
	main_sect +='<div class="col-lg-6 custome_col trasnfer_txt"> <h4 class="sm-t">Transfer NFTs</h4> <p>Experiment with sending NFTs between XP.network, Elrond, BSC etc.</p><a href="https://bridge.xp.network/" class="blueT_btn">Send NFTs <img src="assets/img/icons/blue_arrow.svg" alt="icon"></a> </div>';
	main_sect +='<div class="col-lg-6 custome_col trasnfer_txt"> <h4 class="sm-t">Tokens Transfer</h4> <p>Easily send cryptocurrency from one blockchain to another (coming soon)</p><a href="https://bridge.xp.network/transfer-tokens" class="blueT_btn"> Send Tokens <img src="assets/img/icons/blue_arrow.svg" alt="icon"></a> </div>';
	main_sect +='</div></div>';
	main_sect +='<div class="transferCon_right"><img src="assets/img/xp-net-ap-mob.png" alt="XP-Network" class="mobileonly"> <img src="assets/img/xp-net-ap.svg" alt="XP-Network" class="deskonly"> </div></div></section>';
	main_sect +='<section class="ecosystem_area">';
	main_sect +='<div class="eco_title text-center"> <h2 class="secTitle tcb">An inclusive ecosystem</h2> <p class="sec_t">We aren’t just looping in chains. We are building the largest NFT dApp ecosystem – one that will connect different protocols and remove the entry barriers for non-technical entrepreneurs.</p></div>';
	main_sect +='<div class="moving_line_slider">';
	main_sect +='<div class="moving_line_slider_top">';
	main_sect +='<ul class="marque_top owl-carousel"> <li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-1.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-2.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-3.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-4.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-5.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-1.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-2.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-3.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-4.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclusive_logo-5.svg" alt=""></span></li></ul>';
	main_sect +='</div>';
	main_sect +='<div class="moving_line_slider_bottom">';
	main_sect +='<ul class="marque_bottom owl-carousel"> <li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-1.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-2.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-3.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-4.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-5.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-6.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-1.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-2.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-3.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-4.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-5.svg" alt=""></span></li><li> <span class="exlu_logo"><img src="assets/img/inclusive-logo/inclu_logo-6.svg" alt=""></span></li></ul>';
	main_sect +='</div>';
	main_sect +='</div>';
	main_sect +='</section>';

	main_sect +='<section class="backend_support"> <div class="backend_continer">';
	main_sect +='<div class="backend_left"> <h2 class="secTitle">Backed by the industry’s best</h2> <p class="sec_t">XP.network successfully completed a $4.5M funding round led by such major venture firms as Wings Capital, Blocksync, Master Capital, and NGC Ventures. Thanks to their support, we can integrate more blockchains, faster – all so that you can build your dream NFT dApp and deploy it on any chain, with or without code. </p></div>';
	main_sect +='<ul class="invester_logos owl-carousel"> <li class="invester_log_block"> <a href="#" class="single_investor td1" ><img src="assets/img/investor_logos/NGC.png" alt="Investor"></a> <a href="#" class="single_investor td1" ><img src="assets/img/investor_logos/magnus.png" alt="Investor"></a> </li><li class="invester_log_block"> <a href="#" class="single_investor td2" ><img src="assets/img/investor_logos/EX.png" alt="Investor"></a> <a href="#" class="single_investor td2" ><img src="assets/img/investor_logos/Jun.png" alt="Investor"></a> </li><li class="invester_log_block"> <a href="#" class="single_investor td3" ><img src="assets/img/investor_logos/Masterventure.png" alt="Investor"></a> <a href="#" class="single_investor td3" ><img src="assets/img/investor_logos/blocksync.png" alt="Investor"></a> </li><li class="invester_log_block"> <a href="#" class="single_investor td4" ><img src="assets/img/investor_logos/twinapex.png" alt="Investor"></a> <a href="#" class="single_investor td4" ><img src="assets/img/investor_logos/kosmos.png" alt="Investor"></a> </li><li class="invester_log_block"> <a href="#" class="single_investor td5" ><img src="assets/img/investor_logos/blackdragon.png" alt="Investor"></a> <a href="#" class="single_investor td5" ><img src="assets/img/investor_logos/mintedlab.png" alt="Investor"></a> </li></ul>';
	main_sect +='<div class="text-center"><a href="https://blog.xp.network/the-4-5m-xpnet-pre-sale-is-successfully-completed-b533123673b0" class="blueT_btn">Learn more <img src="assets/img/icons/blue_arrow.svg" alt="icon"></a></div> ';
	main_sect +='</div></section>';

	main_sect +='<!-- /.mian_area -->';

$(document).ready(function(){
	//alert("header");
	$("#main_content_section").html(main_sect);
});