var xp_net = '<section class="xp-banar xtramargin xpbanerxtra"> <img src="/assets/img/xpnetbg.png" alt="" class="xp-banr-bg"> <img src="/assets/img/xp-net/banar-left_art.png" alt="" class="xp-art-1"> <div class="xp-banar-container xtramargin"> <h1 class="inner_banar_title tcb text-center">XPNET已上线</h1> <p class="sec_t">XPNET现可在 <a href="https://pancakeswap.finance/swap?outputCurrency=0x8cf8238abf7b933bf8bb5ea2c7e4be101c11de2a" target="_blank">PancakeSwap</a> 上实时交易并将上线<a href="https://www.gate.io/trade/XPNET_USDT" target="_blank">Gate.io。</a>这绝对是加入XP.network生态系统的最佳时机</p> <ul class="xnet_b_logo"> '
	
xp_net +='<li><img onclick="window.open(`https://pancakeswap.finance/swap?outputCurrency=0x8cf8238abf7b933bf8bb5ea2c7e4be101c11de2a`)" class="click deskonly" src="/assets/img/pancake.png" alt="Icon"><img class="mobileonly" onclick="window.open(`https://pancakeswap.finance/swap?outputCurrency=0x8cf8238abf7b933bf8bb5ea2c7e4be101c11de2a`)"  src="/assets/img/pancakemob.png" alt="Icon"><span class="livenow">上线</span></li> '
	xp_net +='<li><img onclick="window.open(`https://www.gate.io/trade/XPNET_USDT`)" style="" class="deskonly click" src="/assets/img/gateio.png" alt="Icon"><img onclick="window.open(`https://www.gate.io/trade/XPNET_USDT`)" class="mobileonly click" src="/assets/img/gateiomob.png" alt="Icon"><span class="livenow">上线</span></li> '
	
	xp_net +='<li><img onclick="window.open(`https://coinmarketcap.com/currencies/xp-network/`)" class="click deskonly" src="/assets/img/cmc.png" alt="Icon"><img class="mobileonly" onclick="window.open(`https://coinmarketcap.com/currencies/xp-network/`)"  src="/assets/img/cmc.png" alt="Icon"></li> '
	xp_net +='<li><img onclick="window.open(`https://www.coingecko.com/en/coins/xp-network`)" class="click deskonly" src="/assets/img/cg.png" alt="Icon"><img class="mobileonly" onclick="window.open(`https://www.coingecko.com/en/coins/xp-network`)"  src="/assets/img/cg.png" alt="Icon"></li> '

	xp_net +='</ul> </div> <div class="banar_graph"> <img src="/assets/img/xp-net/xp-graph-1.svg" alt="Graph"> </div> </section>'
	
	xp_net +='<section class="claim_xpnet_area"> <div class="claim_xpnet_content"> <h2 class="secTitle text-white"><span class="cominSoo">即将推出</span> <br>获取XPNET</h2> <p class="sec_t owc">早期投资者现在就可以获取他们的XPNET了。<br> 查看已解锁的代币数量。</p> <a href="https://blog.xp.network/the-4-5m-xpnet-pre-sale-is-successfully-completed-b533123673b0" class="blue_btn" style="">获取你的XPNET<img src="/assets/img/icons/arrow-white.svg" alt="arrow"></a> </div> </section>';
// 
	xp_net +='<section class="xpnet-token_area" > <div class="xpnet-token-container"> <div class="xpnet-token-title"> <h2 class="secTitle">XPNET能为你做什么</h2> <p class="sec_t">无需掌握dApp开发技术，<br>就能从$XPNET中获取收益</p> </div> <div class="xpnet-token-list" data-sticky-container> <div class="xpnet-token-outer"> <div class="xpnet-token-box" data-sticky data-sticky-class="sticky" data-margin-top="75" data-margin-bottom="20"> <div class="xpnet-token-inner"> <div class="xpnet-token-box-left"> <h3>PoS验证</h3> <p class="sec_t">成为XP.network平行链上的验证者，促进交易的确认并协助网络运行。您将获得交易费用的一部分作为奖励。另外，引荐提名者可以增加您的股份，让您赚取更多收益。 </p> </div> <div class="xpnet-token-box-right"> <img src="/assets/img/xp-net/tokken/tokken-1.png" alt="Tokken"> </div> </div> </div> </div> <div class="xpnet-token-outer"> <div class="xpnet-token-box" data-sticky data-sticky-class="sticky" data-margin-top="80" data-margin-bottom="20"> <div class="xpnet-token-inner"> <div class="xpnet-token-box-left"> <h3>抵押权益</h3> <p class="sec_t">将您的XPNET抵押给信任的验证者，获取定期奖励。这是利用XP.network代币获利最简单且最安全的方式。无需任何技术经验。</p> </div> <div class="xpnet-token-box-right"> <img src="/assets/img/xp-net/tokken/tokken-2.svg" alt="Tokken"> </div> </div> </div> </div> <div class="xpnet-token-outer"> <div class="xpnet-token-box" data-sticky data-sticky-class="sticky" data-margin-top="85" data-margin-bottom="20"> <div class="xpnet-token-inner"> <div class="xpnet-token-box-left"> <h3>交易</h3> <p class="sec_t">每笔交易都由独立的去中心化验证者仔细检查。内部验证者和桥接中继验证者还会获得优秀工作的奖励。交易费用由提交交易的账户持有人支付。</p> </div> <div class="xpnet-token-box-right"> <img src="/assets/img/xp-net/tokken/tokken-3.svg" alt="Tokken"> </div> </div> </div> </div> <div class="xpnet-token-outer"> <div class="xpnet-token-box" data-sticky data-sticky-class="sticky" data-margin-top="90" data-margin-bottom="20"> <div class="xpnet-token-inner"> <div class="xpnet-token-box-left"> <h3>跨链价值转移</h3> <p class="sec_t">XP.network正在开发的跨链桥，能让代币持有者在桥接区块链之间进行资产的无缝转移。同时，桥梁也是去中心化的。独立的中继验证者会确保区块链之间资产的完整性，不会丢失或复制任何内容。</p> </div> <div class="xpnet-token-box-right"> <img src="/assets/img/xp-net/tokken/tokken-4.svg" alt="Tokken"> </div> </div> </div> </div> <div class="xpnet-token-outer"> <div class="xpnet-token-box" > <div class="xpnet-token-inner"> <div class="xpnet-token-box-left"> <h3>治理</h3> <p class="sec_t">XP.network将逐步引入去中心化的治理机制，允许XPNET持有者来决定网络应如何发展。理事会提出提案，由社区投票决定。</p> </div> <div class="xpnet-token-box-right"> <img src="/assets/img/xp-net/tokken/tokken-5.svg" alt="Tokken"> </div> </div> </div> </div> </div> </div> </section>';

	xp_net +='<section  id="token-metrics" class="metrics_area">'
	xp_net +='<img class="metrics_art-1" src="/assets/img/xp-net/metrics_art-1.png" alt="" style="position: absolute;z-index: -1;"> <img class="metrics_art-2" src="/assets/img/xp-net/metrics_art-2.png" alt="" style="position: absolute;z-index: -1;">'
	xp_net +=' <div  class="merics_contaienr"> <h2 class="secTitle text-center">代币指标</h2> <ul class="metri_rising"> <li> <span class="rising_tit">总供应量</span> <span class="rising_amo">1,000,000,000</span> </li> <li> <span class="rising_tit">筹集</span> <span class="rising_amo">$5,876,250</span> </li> <li> <span class="rising_tit">TGE市值</span> <span class="rising_amo">$2,250,000</span> </li> <li> <span class="rising_tit">TGE流动资金</span> <span class="rising_per">11.25%</span> </li> </ul> <div class="metrics_table" id="content"> <table class="table metricsTable"> <thead> <tr> <th>融资轮</th> <th>价格</th> <th>最短生效期（月）</th> <th>行权期（月）</th> <th>FDV</th> </tr> </thead> <tbody> <tr> <td>种子 <span class="soldOut">售罄</span></td> <td>$0.0075</td> <td>2</td> <td>12</td> <td>$7,500,000</td> </tr> <tr> <td>战略 <span class="soldOut">售罄</span></td> <td>$0.010</td> <td>1</td> <td>12</td> <td>$10,000,000</td> </tr> <tr> <td>私人 <span class="soldOut">售罄</span></td> <td>$0.015</td> <td>0.5</td> <td>9</td> <td>$15,000,000</td> </tr> <tr> <td>公共<span class="soldOut">售罄</span></td> <td>$0.020</td> <td></td> <td></td> <td>$20,000,000</td> </tr> </tbody> </table> </div>'
	xp_net +=' <div class="mobileonly"> <div class="table_scrol"> <button id="scroll_left"><img src="/assets/img/tech_page/arowLeft.svg" alt=""></button> <button id="scroll_right"><img src="/assets/img/tech_page/arrowRight.svg" alt=""></button> </div> </div> '
	xp_net +='<div class="metRise_graph"> <img class="deskonly" src="/assets/img/xp-net/pie-chart-ch-desktop.svg" alt="Mertise Graph"><img class="mobileonly" src="/assets/img/xp-net/pie-chart-ch-mob.svg" alt="Mertise Graph"> </div> '
	xp_net +='</div> </section>';

$(document).ready(function(){
	//alert("header");
	$("#xpnet_bodies").html(xp_net);
});